// Product Data
const products = [
  {
    id: 1,
    name: "Mango Achar",
    category: "veg",
    price: 210,
    weight: "380gm",
    image: "/images/products/MangoPickle.JPG",
    description: "",
  },
  {
    id: 2,
    name: "Radish Pickle (Mula Ko Achar)",
    category: "veg",
    price: 170,
    weight: "350gm",
    image: "/images/products/RadishPickle.JPG",
    description: "",
  },
  {
    id: 3,
    name: "Chicken Achar",
    category: "meat",
    price: 700,
    weight: "350gm",
    image: "/images/products/ChickenPickle.JPG",
    description: "",
  },
  {
    id: 4,
    name: "Dry Fish Pickle (Sidra ko Achar)",
    category: "meat",
    price: 360,
    weight: "350gm",
    image: "/images/products/DryFish.JPG",
    description: "",
  },
  {
    id: 5,
    name: "Round Chilli Pickle (Akbare ko Achar)",
    category: "veg",
    price: 320,
    weight: "320gm",
    image: "/images/products/akbare.jpg",
    description: "",
  },
  {
    id: 6,
    name: "Timmur ko Chhop",
    category: "veg",
    price: 145,
    weight: "100gm",
    image: "/images/products/timbur.jpg",
    description: "",
  },
  {
    id: 7,
    name: "Szechuan Sauce (Piro Achar)",
    category: "veg",
    price: 225,
    weight: "350gm",
    image: "/images/products/SzechuanSauce.JPG",
    description: "",
  },
];
